# Generated by Django 2.1.7 on 2019-03-06 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('idBus', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidadPasajeros', models.IntegerField(default=10)),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioServicio',
            fields=[
                ('idHorarioServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fechaServicio', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroAsiento', models.CharField(max_length=2)),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.HorarioServicio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacionPais', models.CharField(max_length=15)),
                ('nombrePrimario', models.CharField(max_length=45)),
                ('nombreSecundario', models.CharField(max_length=45, null=True)),
                ('apPaterno', models.CharField(max_length=45)),
                ('apMaterno', models.CharField(max_length=45)),
                ('fecIncorporacion', models.DateField(auto_now_add=True)),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('idTrayecto', models.AutoField(primary_key=True, serialize=False)),
                ('ciudadSalida', models.CharField(max_length=100)),
                ('ciudadLlegada', models.CharField(max_length=100)),
                ('fecIngresoReg', models.DateTimeField(auto_now_add=True)),
                ('fecUltActReg', models.DateTimeField(auto_now_add=True)),
                ('estadoReg', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.TipoPersona'),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.Persona'),
        ),
        migrations.AddField(
            model_name='horarioservicio',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.Persona'),
        ),
        migrations.AddField(
            model_name='horarioservicio',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBuses.Trayecto'),
        ),
    ]
